-- Insertando 5 usuarios falsos en la tabla 'users'
INSERT INTO users (pwhash, provider, name, lastname, email, phone, description, proficiency, trainingPreferences, img, country, city, latitude, longitude, isSetup, tableVersion, monday, tuesday, wednesday, thursday, friday, saturday, sunday, timetable1, timetable2) VALUES
('hash1', 'local', 'Juan', 'Pérez', 'juan.perez@example.com', '+123456789', 'Descripción de Juan', 'Intermedio', 'Prefiero entrenamiento al aire libre', 'img2.jpg', 'México', 'Ciudad de México', '19.4326', '-99.1332', TRUE, 1, TRUE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, 8, 10),
('hash2', 'google', 'Ana', 'Gómez', 'ana.gomez@example.com', '+987654321', 'Descripción de Ana', 'Avanzado', 'Prefiero entrenamiento en casa', 'img3.jpg', 'España', 'Madrid', '40.4168', '-3.7038', FALSE, 0, FALSE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, 9, 11),
('hash3', 'local', 'Carlos', 'Martínez', 'carlos.martinez@example.com', '+112233445', 'Descripción de Carlos', 'Principiante', 'Prefiero entrenamiento en grupo', 'img4.jpg', 'Argentina', 'Buenos Aires', '-34.6037', '-58.3816', TRUE, 2, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, 7, 9),
('hash4', 'google', 'Lucía', 'Fernández', 'lucia.fernandez@example.com', '+554433221', 'Descripción de Lucía', 'Avanzado', 'Prefiero entrenamiento individual', 'img5.jpg', 'Chile', 'Santiago', '-33.4489', '-70.6693', FALSE, 1, FALSE, TRUE, FALSE, TRUE, FALSE, TRUE, FALSE, 10, 12),
('hash5', 'local', 'Pedro', 'López', 'pedro.lopez@example.com', '+667788990', 'Descripción de Pedro', 'Intermedio', 'Prefiero entrenamiento en la mañana', 'img6.jpg', 'Colombia', 'Bogotá', '4.7110', '-74.0721', TRUE, 0, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, 6, 8),
('hash6', 'google', 'María', 'Sánchez', 'maria.sanchez@example.com', '+556677889', 'Descripción de María', 'Principiante', 'Prefiero entrenamiento con pesas', 'img7.jpg', 'Perú', 'Lima', '-12.0464', '-77.0428', FALSE, 2, FALSE, FALSE, TRUE, TRUE, TRUE, FALSE, TRUE, 7, 10),
('hash7', 'local', 'Jorge', 'Díaz', 'jorge.diaz@example.com', '+441122334', 'Descripción de Jorge', 'Avanzado', 'Prefiero entrenamiento en la noche', 'img8.jpg', 'Uruguay', 'Montevideo', '-34.9011', '-56.1645', TRUE, 1, TRUE, TRUE, FALSE, FALSE, TRUE, TRUE, FALSE, 8, 11),
('hash8', 'google', 'Elena', 'Ruiz', 'elena.ruiz@example.com', '+998877665', 'Descripción de Elena', 'Intermedio', 'Prefiero entrenamiento en interiores', 'img9.jpg', 'Venezuela', 'Caracas', '10.4806', '-66.9036', FALSE, 0, FALSE, FALSE, TRUE, TRUE, FALSE, FALSE, TRUE, 9, 12),
('hash9', 'local', 'Miguel', 'Torres', 'miguel.torres@example.com', '+556644332', 'Descripción de Miguel', 'Principiante', 'Prefiero entrenamiento funcional', 'img10.jpg', 'Bolivia', 'La Paz', '-16.5000', '-68.1500', TRUE, 2, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, 6, 9),
('hash10', 'google', 'Carmen', 'Ramírez', 'carmen.ramirez@example.com', '+443322110', 'Descripción de Carmen', 'Avanzado', 'Prefiero entrenamiento con entrenador personal', 'img11.jpg', 'Paraguay', 'Asunción', '-25.2637', '-57.5759', FALSE, 1, FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, 10, 12);
